### ISSUE TITLE
Storage path in options (job)

### ISSUE THREAD

**Issue by Menahem1** [rundeck/terraform-provider-rundeck#14]
Hello,

In the option block, i don't see the "storage path" parameter as on the interface

![image](https://user-images.githubusercontent.com/1558463/41045356-8de8632a-69a8-11e8-9fc6-8af04519fe7d.png)

Any idea when it will be available ?

Thanks

**Comment by MoonMoon1919** [comment]
After looking at the go-rundeck-api package this is already implemented there, so it'll just be a matter of adding the additional option field. I can take a crack at this hopefully in the next few days.

**Comment by renperez** [comment]
cool! thanks @MoonMoon1919

**Comment by diogokiss** [comment]
Any updates on that, @MoonMoon1919 ? I'm in need of this feature as well. :-)

**Comment by rado1591** [comment]
Hi, any idea when this will be available officially?
