### ISSUE TITLE
Feature request: Support creating jobs with retry configurations

### ISSUE THREAD

**Issue by josemaia** [rundeck/terraform-provider-rundeck#36]
Currently, via the UI or YAML you can configure retry parameters for a job.

For example, assuming we want to retry 3 times, with a delay of 1h between each retry, it would look like this.
YAML:
```
  retry:
      delay: 1h
      retry: 3
```

UI:
![image](https://user-images.githubusercontent.com/6306304/63681559-e7b3af00-c7ed-11e9-95db-40155c9b6481.png)

### Terraform Version
```
Terraform v0.12.5
+ provider.rundeck v0.4.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- provider.rundeck
- provider.rundeck, resource rundeck_job

### Expected Behavior
It should be possible to use Terraform to configure a job with these parameters

### Actual Behavior
Option is not available in the HCL resource

**Comment by AndreyAndreevStenn** [comment]
May I ask why the PR with adding the retry delay parameter is not merged but closed? Is it possible to still add the retry_delay parameter to the rundeck_job resource configuration?

**Comment by fdevans** [comment]
My guess is that between the time the original PR was created and the time it was closed there was a significant rewrite of the provider.  If this is still needed and not implemented please open a new Issue with details from a current Rundeck version.
