### ISSUE TITLE
Rundeck throwing "x509: certificate signed by unknown authority"

### ISSUE THREAD

**Issue by gangadhar01a** [rundeck/terraform-provider-rundeck#41]
Rundeck is running behind proxy (Nginx), we are trying to create project using terraform. Unfortunately, it resulted in error

main.tf
"provider "rundeck" {
  url         = "https://XYZ.com"
  auth_token  = "*******************"
}
resource "rundeck_project" "EnterpriseApplications" {
  name        = "EnterpriseApplications"
  description = "Application for managing ERP"

resource_model_source {
    type = "file"
    config = {
      format = "resourcexml"
       file = "/var/rundeck/projects/test1/etc/resources.xml"
    }
  }
  default_node_file_copier_plugin = "stub"
}"

Terraform init ran without any errors, when I ran terraform apply it resulted in following error 
"_rundeck_project.EnterpriseApplications: rundeck.BaseClient#ProjectCreate: Failure sending request: StatusCode=0 -- Original Error: Post https://rundeck-XXXXXX/api/14/projects: x509: certificate signed by unknown authority_"

Version: Terraform v0.11.11

### Expected Behavior
It should create required resource 

### Actual Behavior
Throwing a certificate related error.

**Comment by mignat** [comment]
Had this happen to me yesterday, i fixed it by adding the full certificate chain instead of just the certificate to Nginx

**Comment by sangeethdba** [comment]
@jtobard appreciate if the Support to provide ca certificate is added

**Comment by sangeethdba** [comment]
@grubernaut

**Comment by fdevans** [comment]
Please try to recreate this issue on the current Terraform and provider version. If you still have trouble open a new issue with steps to reproduce please.
