### ISSUE TITLE
Terrafrom Rundeck provider not respecting "allow_unverified_ssl"

### ISSUE THREAD

**Issue by gangadhar01a** [rundeck/terraform-provider-rundeck#42]
Hi,

I am trying to bypass SSL Check to work with rundeck. Unfortunately, its showing an **"Error: Unsupported argument** error.

**main.tf**

provider "rundeck" {
  url         = "https://XXXX"
  api_version = "24"
  auth_token  = "ABCD"
  allow_unverified_ssl = true
}

resource "rundeck_project" "EnterpriseApplications" {
  name        = "EnterpriseApplications"
  description = "Application for managing ERP"

  resource_model_source {
    type = "file"

    config = { 
      format = "resourcexml"

      file = "/var/rundeck/projects/test1/etc/resources.xml"
    }   
  }
  default_node_file_copier_plugin = "stub"
}

Terrafrom version: v0.12.9
OS - centOS 7

Expected: it should bypass the SSL check and create the required project in rundeck.

Actual: Error: Unsupported argument
on main.tf line 5, in provider "rundeck":
   5:   allow_unverified_ssl = true

**Comment by fdevans** [comment]
Please try to recreate this issue on the current Terraform and provider version. If you still have trouble open a new issue with steps to reproduce please.
