### ISSUE TITLE
Error Handlers not supported 

### ISSUE THREAD

**Issue by gangadhar01a** [rundeck/terraform-provider-rundeck#43]
Hi there,

### Terraform Version

0.12.9
### Affected Resource(s)

rundeck_job

### Issue

I have read the documentation to create a workflow for the job and noticed error handling support has been missing at command level.

### Expected Behavior
What should have happened?

### Actual Behavior
What actually happened?
Feature doesn't exist.

**Comment by pkrauss-prot** [comment]
Can we get this re-opened since this feature is still missing, given that the pull request was closed?

**Comment by fdevans** [comment]
Please try to recreate this issue on the current Terraform and provider version. If you still have trouble open a new issue with steps to reproduce please.
