### ISSUE TITLE
script_interpreter block in job command does not work

### ISSUE THREAD

**Issue by c-elliott** [rundeck/terraform-provider-rundeck#71]
```
chris-mbp: menlo-dev> terraform version
Terraform v0.13.6
+ provider registry.terraform.io/hashicorp/aws v3.51.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/rundeck/rundeck v0.4.2
+ provider registry.terraform.io/terraform-providers/rundeck v0.4.0
```

As per https://registry.terraform.io/providers/rundeck/rundeck/latest/docs/resources/job I should be able to add a script_interpreter block within the command block like this:

command {
  script_file      = "/path/to/script.py"
  script_file_args = "arg1 arg2"
  script_interpreter {
    invocation_string = "/usr/bin/python3"
  }
}

It fails with this error:

`Blocks of type "script_interpreter" are not expected here. `

I have also tried defining this as different datatypes which fail with the same error. I had a look at rundeck/resource_job.go and it looks OK.

Can anyone else reproduce this?

Thanks

**Comment by fdevans** [comment]
@c-elliott As we catch up on addressing these old Issues in the list were you able to work past this?  If there are still issues can you reopen a new issue with steps to reproduce it?
