### ISSUE TITLE
Feature request: Command that can run a job from another project

### ISSUE THREAD

**Issue by absmartin** [rundeck/terraform-provider-rundeck#80]
In the command {} block, if you want to include a job from another project, you need to pass the project or uuid which both return "not expected".

Reading the docs, it specifically says:
"A job block, described below, causes another job within the same project to be executed as a command."

Can the project and uuid parameter be added so that it can run a job from another project?

**Comment by fdevans** [comment]
As this is a community supported project we are open to Pull Requests that would add this as a option.

**Comment by jmthomas-mitre** [comment]
It does appear that there was a merge request associated with this feature for another issue regarding this capability: https://github.com/rundeck/terraform-provider-rundeck/issues/7 The PR submitter eventually closed the PR though.

**Comment by fdevans** [comment]
Added to 0.4.8 thanks to [b0tting](https://github.com/b0tting)
