### ISSUE TITLE
Release provider for ARM/darwin_arm64

### ISSUE THREAD

**Issue by fardin01** [rundeck/terraform-provider-rundeck#81]
### Terraform Version
```
$ terraform1_1_9 -v
Terraform v1.1.9
on darwin_arm64
```

### Affected Resource(s)
N/A

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
N/A

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
N/A

### Actual Behavior
N/A

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
N/A

### Important Factoids
I got around this issue by compiling the provider locally and overriding it in `~/.terraformrc` and it works okay. However, we commit `.terraform.lock.hcl` file, and of course the file contains a different hash for the locally compiled provider, so the code isn't going to run for other colleagues on Intel CPUs and our build pipeline.

I see that there is an ARM64 for Linux here in Github, but I cannot find anything in Terraform's registry.

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
No.

**Comment by fdevans** [comment]
I believe this is completed.  Please reopen a new case if you continue to have issues.
