### ISSUE TITLE
Invocation String options

### ISSUE THREAD

**Issue by kizzie** [rundeck/terraform-provider-rundeck#9]
Hello! I don't suppose there are any plans to add an option for the invocation string to be set via terraform is there? Or am I just missing it? (http://rundeck.org/docs/manual/jobs.html#advanced-script-options). 

### Terraform Version
0.10.0 (although terraform version isn't really a problem here as long as its on 0.10.x)

### Affected Resource(s)
rundeck_job -> command -> inline_script

**Comment by richardgavel** [comment]
Any updates on this?

**Comment by kizzie** [comment]
Wow. I had entirely forgotten about this. We just started updating and keeping our own version of the provider... not sure it will ever be merged!

**Comment by richardgavel** [comment]
Don't suppose that fork is sitting in Github that I can see? I might just fork and submit a PR for this change to the main repo.

**Comment by kizzie** [comment]
Sadly not - I'll ask if I am allowed to put it all in there though. For this specific thing https://github.com/rundeck/terraform-provider-rundeck/pull/10 fixes it though :)

**Comment by richardgavel** [comment]
Thanks, I was struggling a bit where some of the changes would go, this helps

**Comment by richardgavel** [comment]
Reimplemented against current master as https://github.com/rundeck/terraform-provider-rundeck/pull/64

**Comment by Onelvis** [comment]
Any plans to also add the file extension option? I'm having some issues with Windows nodes in which, by default, the temp script gets copied as a `.bat` file, which means that any Powershell specific cmdlet is not being recognized (I've tried setting the `invocation_string` to `powershell.ps1 ${scriptfile}.ps1`, but this only results on the temp file being copied as `script.tmp.bat.ps1`, thus failing). 

This is explained [in the rundeck doc page about builtin node steps](https://docs.rundeck.com/docs/manual/node-steps/builtin.html#changing-the-file-extension)

**Comment by fdevans** [comment]
See comments on #10 to finalize this.

**Comment by fdevans** [comment]
Invocation string should be supported.
