### ISSUE TITLE
Feature request: Add support for username and password

### ISSUE THREAD

**Issue by sanderdescamps** [rundeck/terraform-provider-rundeck#91]
Hi there,

Currently the provider only supports token authentication. But tokens expire and need to be generated. We use Rundeck in our trainings environments and deploy it fully automatic. Therefor it would be nice if the provider provides support for username and password. 

I've implemented the feature and the PR will follow soon. Feel free to provide comments or feedback.

**Comment by fdevans** [comment]
Closed with #103
